esprit:
  filesystem:
    repository:
      root: espritFileRepo
      entities: users,posts
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB